name: twit
version: 0.0.3
description: Dart port of Tolga Tezel's Twitter client.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/twit
dependencies:
  crypto: ">=2.0.0 <3.0.0"
  http: ">=0.11.0 <1.0.0"
  owl: ">=0.1.1 <1.0.0"
  random_string: ">=0.0.1 <0.1.0"
dev_dependencies:
  build_runner: ">=0.3.0 <0.4.0"
  dotenv: ">=0.1.3 <0.2.0"
  owl_codegen: ">=0.1.1 <1.0.0"
  test: ">=0.12.0 <0.13.0"